### ISSUE TITLE
Package for Frameworks

### ISSUE THREAD

**Issue by KielD-01** [AdminAnticaptcha/anticaptcha-php#3]
Hello Dear Developers!
I want to ask You to make anticaptcha as composer package.
Because i'd like to have this package using in my project.

**Comment by tangent-tech** [comment]
+1

**Comment by coder77** [comment]
+1

**Comment by KielD-01** [comment]
Guys, i've done it today
@tangent-tech , @coder77  - [https://github.com/KielD-01/anticaptcha-php](Link to my repo)
